# Generated by Django 4.2.7 on 2023-11-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=255)),
                ('Marca', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('Ano', models.IntegerField()),
            ],
        ),
    ]
