# Generated by Django 4.2.7 on 2023-11-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Ano',
            new_name='Anio',
        ),
    ]
